### ISSUE TITLE
Can't click anything

### ISSUE THREAD

**Issue by jaredhasenklein** [arimb/ZebraPlot#1]
None of the buttons/menus work for me.
[![Image from Gyazo](https://i.gyazo.com/55d29c8cae5fbe658b2e5faf6f131b28.gif)](https://gyazo.com/55d29c8cae5fbe658b2e5faf6f131b28)
Latest Chrome, Windows 10

**Comment by arimb** [comment]
I can't recreate this issue on the same browser and OS. I just posted an update that fixes a few other problems, see if that fixes this problem too. If not, it looks like the script is crashing somewhere. Can you open the dev tools and see if it's throwing an error.

**Comment by jaredhasenklein** [comment]
Still not working. Hopefully this is helpful to you:
![image](https://user-images.githubusercontent.com/22439365/74578907-453ae400-4f65-11ea-94b5-663cfc5e6ab0.png)
Tried it on multiple browsers with no luck.

**Comment by jaredhasenklein** [comment]
Also, it works when connected to the same network from my phone, so it's not a network issue.

**Comment by arimb** [comment]
It seems your computer isn't loading JQuery for some reason. Not really sure why that would happen, I haven't heard anyone else say they have the same issue. I wonder if you try to go to the URL directly from your browser if it loads or if it still throws an error.

https://code.jquery.com/jquery-3.4.1.min.js

**Comment by jaredhasenklein** [comment]
Very weird but... I went the jquery link above and it threw a network error. But then, 3 seconds later it automatically refreshed and worked. Then, I returned to your site and it started working again. I'm guessing there was a weird issue with cache on my end from the last tie I accessed jquery and that this has nothing to do with your site. Thx for help with debugging.
